name: Request Category
about: Request a new category for Guides, Blogs, Quizzes, or Software
title: "[CATEGORY REQUEST]"
labels: enhancement
body:
- type: dropdown
  - id: subpage
  - name: subpage
  - attributes:
    label: Pick a target subpage for your category request
    options:
    - Docs (both "Blogs" & "Quizzes")
    - Docs/Blogs
    - Docs/Guides
    - Quizzes
    - Software
    validations:
      required: true
- type: input
  - label: Category title
  - id: category-title
  - name: category-title
  - placeholder: Category Title
    validations:
      required: true
  - type: textarea
    - id: additional-information
    - name: additional-information
    - label: Additional information
  - placeholder: Provide additional information on the category; give examples of possible articles, blogs, guides, or, quizzes that may appear here.
